
const $=x=>document.getElementById(x);let token=localStorage.saToken||"",S=null,cache=[];
async function api(action,payload={}){const r=await fetch(SEWANGAN_CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain"},body:JSON.stringify({action,token,payload})});const j=await r.json();if(!j.ok)throw Error(j.error);return j.data}
async function login(){try{const d=await api("adminLogin",{user:$("user").value,password:$("pass").value});token=d.token;localStorage.saToken=token;S=d;start()}catch(e){$("msg").textContent=e.message}}
function logout(){localStorage.removeItem("saToken");location.reload()}function start(){$("login").classList.add("hidden");$("app").classList.remove("hidden");$("who").textContent=S.user.Name||S.user.RoleID;dash()}
function dash(){$("view").innerHTML=`<div class="card hero"><h2>Administration Dashboard</h2><p>Head Office - Sursand and National Office - Delhi are maintained separately.</p></div><div class=grid><div class=card><h3>Joining Requests</h3><button onclick=applications()>Review</button></div><div class=card><h3>Members</h3><button onclick=members()>Open Cards</button></div><div class=card><h3>Office Hierarchy</h3><button onclick=offices()>Open Registers</button></div><div class=card><h3>Main App Access</h3><button onclick=accessMatrix()>Configure</button></div></div>`}
async function applications(){const r=await api("list",{module:"membershipapplications"});$("view").innerHTML=`<h2>New Member Joining Requests</h2><div class=grid>${r.map(a=>`<div class="card member"><h3>${a.Name}</h3><p>${a.MemberType||a.DesignationID}</p><p>${a.Mobile} • ${a.Panchayat||a.Block||""}</p><p>Source: ${a.Source||""}${a.ReferredByName?` • Referred by ${a.ReferredByName}`:""}</p><span class=status>${a.ApplicationStatus}</span>${a.ApplicationStatus!=="Approved"?`<p><button onclick="approve('${a.ApplicationID}')">Approve Member</button></p>`:""}</div>`).join("")||"<div class=card>No requests.</div>"}</div>`}
async function approve(id){if(!confirm("Approve this member and create login credentials?"))return;try{const d=await api("approveMember",{applicationId:id});alert(`Approved.\nLogin: ${d.login.phone}\nDefault password: ${d.login.defaultPassword}`);memberCard(d.member.MemberID)}catch(e){alert(e.message)}}
async function members(){const r=await api("list",{module:"members"});$("view").innerHTML=`<h2>Member Register</h2><div class=grid>${r.map(m=>`<div class="card member"><h3>${m.Name}</h3><p>${m.Designation||""}</p><p>${m.MemberID}</p><p>${m.Panchayat||m.Block||m.District||m.State||""}</p><span class="status ${String(m.Status).toLowerCase()}">${m.Status}</span><p><button onclick="memberCard('${m.MemberID}')">View Full Details</button></p></div>`).join("")}</div>`}
async function memberCard(id){const d=await api("memberDetails",{memberId:id}),m=d.member;$("view").innerHTML=`<h2>${m.Name}</h2><div class=grid><div class="card member"><h3>Member Details</h3>${Object.entries(m).map(([k,v])=>`<p><b>${k}:</b> ${v||""}</p>`).join("")}</div><div class=card><h3>Actions</h3><button onclick="showID('${m.MemberID}')">Generate / Share ID Card</button><br><br><button onclick="showLetter('${m.MemberID}')">Appointment Letter PDF</button><br><br><button class=green onclick="shareAPK('${m.Mobile}')">Share APK</button><br><br><button class=green onclick="resetPw('${m.MemberID}')">Reset & Share Login</button><br><br><button onclick="setStatus('${m.MemberID}','Active')">Active</button> <button onclick="setStatus('${m.MemberID}','Inactive')">Inactive</button> <button class=red onclick="setStatus('${m.MemberID}','Blacklisted')">Blacklist</button></div></div>`}
async function resetPw(id){try{const d=await api("resetPassword",{memberId:id});const t=`Sewangan Login\nPhone: ${d.phone}\nPassword: ${d.newPassword}\nPlease change password after login.`;if(navigator.share)navigator.share({text:t});else{navigator.clipboard.writeText(t);alert(t)}}catch(e){alert(e.message)}}
async function setStatus(id,status){const reason=prompt("Reason for "+status,"");if(reason===null)return;await api("setMemberStatus",{memberId:id,status,reason});memberCard(id)}
async function showID(id){const d=await api("memberDetails",{memberId:id}),m=d.member;$("view").innerHTML=`<div class=no-print><button onclick=print()>Download / Print PDF</button> <button class=green onclick="sharePage()">Share</button></div><div class=idcard><div class=idhead><img src=assets/sewangan-logo.png><div><b>SEWANGAN CHARITABLE TRUST</b><br><small>MEMBER IDENTITY CARD</small></div></div><div class=idbody><img class=photo src="${m.PhotoURL||'assets/sewangan-logo.png'}"><div><h3>${m.Name}</h3><div>${m.Designation||""}</div><div><b>ID:</b> ${m.MemberID}</div><div><b>Area:</b> ${m.Panchayat||m.Block||m.District||""}</div><div><b>Phone:</b> ${m.Mobile}</div><div><b>Joining:</b> ${m.JoinDate||""}</div><div><b>Valid:</b> ${m.ValidUntil||""}</div></div></div><div class=idfoot>www.sewangan.in</div></div>`}
async function showLetter(id){const d=await api("memberDetails",{memberId:id}),m=d.member;$("view").innerHTML=`<div class=no-print><button onclick=print()>Download / Print PDF</button> <button class=green onclick=sharePage()>Share</button></div><div class=letter><div class=letterhead><img src=assets/sewangan-logo.png><h2>SEWANGAN CHARITABLE TRUST</h2><b>MEMBERSHIP APPOINTMENT LETTER</b></div><p>Date: ${new Date().toLocaleDateString()}</p><p>To,<br><b>${m.Name}</b><br>${m.Address||""}<br>${m.District||""}, ${m.State||""}<br>Contact: ${m.Mobile||""}</p><p><b>Subject: Appointment as ${m.Designation||"Member"} in Sewangan Charitable Trust</b></p><p>Dear ${m.Name},</p><p>We are pleased to inform you that you have been appointed as <b>${m.Designation||"Member"}</b> in Sewangan Charitable Trust with effect from ${m.JoinDate||""}.</p><h3>Roles & Responsibilities</h3><ul><li>Participate actively in Trust programs, meetings and activities.</li><li>Support organizational initiatives and social welfare projects.</li><li>Promote the mission and objectives of the organization.</li><li>Maintain discipline and coordinate effectively with team members.</li><li>Represent the organization responsibly.</li></ul><h3>Terms & Conditions</h3><ol><li>This position may be voluntary unless specified otherwise.</li><li>Follow all rules, regulations and policies.</li><li>Maintain confidentiality of organizational information.</li><li>Membership may be terminated for misconduct or policy violations.</li></ol><h3>Member Details</h3><p>ID Card No.: ${m.MemberID}<br>Designation: ${m.Designation||""}<br>Department: ${m.Department||"General"}<br>Validity: ${m.ValidUntil||""}</p><br><br><p><b>Authorized Signatory</b><br>Sewangan Charitable Trust</p></div>`}
async function offices(){const r=await api("officeCards");$("view").innerHTML=`<h2>Office Hierarchy & Registers</h2><div class=grid>${r.map(o=>`<div class="card office"><h3>${o.OfficeName}</h3><p>${o.OfficeType}</p><p>${[o.Block,o.District,o.State].filter(Boolean).join(", ")}</p><p>Members: <b>${o.MemberCount}</b> • Lower Offices: <b>${o.LowerOfficeCount}</b></p><button>View Register</button></div>`).join("")}</div>`}
async function accessMatrix(){const r=await api("mainAccess");cache=r;const ds=[...new Set(r.map(x=>x.DesignationID))];$("view").innerHTML=`<h2>Main App Access — Designation Wise</h2><div class=card><label>Designation</label><select id=des onchange=drawAccess()>${ds.map(x=>`<option>${x}</option>`).join("")}</select><div id=matrix class=tablewrap></div><button onclick=saveAccess()>Save Access</button></div>`;drawAccess()}
function drawAccess(){const id=$("des").value,rs=cache.filter(x=>x.DesignationID===id);$("matrix").innerHTML=`<table><tr><th>Module</th><th>View</th><th>Add</th><th>Edit</th><th>Delete</th><th>Approve</th><th>Scope</th></tr>${rs.map(r=>`<tr><td>${r.ModuleKey}</td>${["View","Add","Edit","Delete","Approve"].map(p=>`<td><input class="tick acc" data-m="${r.ModuleKey}" data-p="${p}" type=checkbox ${String(r[p]).toLowerCase()==="true"?"checked":""}></td>`).join("")}<td><select class=scope data-m="${r.ModuleKey}"><option ${r.Scope==="Own"?"selected":""}>Own</option><option ${r.Scope==="Own + Direct Lower"?"selected":""}>Own + Direct Lower</option><option ${r.Scope==="Own + All Lower"?"selected":""}>Own + All Lower</option></select></td></tr>`).join("")}</table>`}
async function saveAccess(){const id=$("des").value,rows=cache.filter(x=>x.DesignationID===id);rows.forEach(r=>{document.querySelectorAll(`.acc[data-m="${r.ModuleKey}"]`).forEach(c=>r[c.dataset.p]=c.checked);r.Scope=document.querySelector(`.scope[data-m="${r.ModuleKey}"]`).value});await api("saveMainAccess",{rows});alert("Access saved")}
async function generic(m){const r=await api("list",{module:m});$("view").innerHTML=`<h2>${m}</h2><div class=grid>${r.map(x=>`<div class=card>${Object.entries(x).slice(0,10).map(([k,v])=>`<div><b>${k}:</b> ${v||""}</div>`).join("")}</div>`).join("")||"<div class=card>No records.</div>"}</div>`}
function shareAPK(){const t="Download Sewangan App: "+SEWANGAN_CONFIG.APK_URL;if(navigator.share)navigator.share({text:t});else{navigator.clipboard.writeText(t);alert(t)}}function sharePage(){if(navigator.share)navigator.share({url:location.href});else alert("Use browser Share / Print to PDF.")}
(async()=>{if(token)try{S=await api("session");start()}catch(e){localStorage.removeItem("saToken")}})();
