
const $=id=>document.getElementById(id);let token=localStorage.APP_TOKEN||"",B=null,current={key:"",name:"",rows:[],schema:null};
async function api(action,payload={}){let r=await fetch(APP_CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,token,payload})}),t=await r.text();if(t.trim().startsWith("<"))throw Error("API connection problem. Update Apps Script deployment.");let j=JSON.parse(t);if(!j.ok)throw Error(j.error);return j.data}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function toast(s){let d=document.createElement("div");d.className="toast";d.textContent=s;document.body.appendChild(d);setTimeout(()=>d.remove(),2600)}
function modal(title,html){let d=document.createElement("div");d.className="modal";d.innerHTML=`<div class=modalbox><div class=modalhead><h3>${esc(title)}</h3><button class=x onclick="this.closest('.modal').remove()">×</button></div>${html}</div>`;document.body.appendChild(d);return d}
function togglePw(id,b){const x=document.getElementById(id);if(!x)return;const show=x.type==="password";x.type=show?"text":"password";b.textContent=show?"🙈":"👁"}
function icon(k){let x={members:"👥",membership_applications:"✓",employees:"♟",volunteers:"🙋",donations:"₹",goods_donations:"🎁",donors:"🤝",receipts:"🧾",programs:"◎",projects:"▣",events:"◉",campaigns:"📣",beneficiaries:"❤",help_requests:"🆘",accounts:"▤",transactions:"⇄",cash_book:"₹",bank_book:"🏦",ledger:"▥",payments:"₹",vouchers:"▧",expenses:"↘",inventory:"▦",purchases:"🛒",vendors:"♜",assets:"◆",documents:"▤",letters:"✉",certificates:"▧",notifications:"🔔",offices:"⌘",settings:"⚙",users:"♟",roles:"🔐",audit_log:"☷",payment_gateways:"₹",salary_slips:"₹",payroll:"₹",employee_attendance:"✓",tasks:"☑",grievances:"!",training:"◈",compliance:"✓",partnerships:"🤝",impact_records:"◉"};return x[k]||"◆"}
let stimer;async function globalSearch(q){clearTimeout(stimer);let box=$("gsr");if(!q||q.trim().length<2){if(box)box.innerHTML="";return}stimer=setTimeout(async()=>{try{let r=await api("globalSearch",{q});box.innerHTML=r.length?r.map((x,i)=>`<div class=searchitem onclick='searchOpen(${JSON.stringify(x).replace(/'/g,"&#39;")})'><b>${esc(x.title)}</b><small>${esc(x.moduleName)} • ${esc(x.subtitle)}</small></div>`).join(""):`<div class=searchitem>No result</div>`}catch(e){box.innerHTML=`<div class=searchitem>${esc(e.message)}</div>`}},300)}
function searchOpen(x){document.querySelectorAll(".searchresults").forEach(e=>e.innerHTML="");recordDetail(x.record,x.module,x.moduleName)}
function moduleSearch(q){q=(q||"").toLowerCase();let r=current.rows.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q));renderCards(r)}
function cardTitle(x){return x.Name||x.EmployeeName||x.OfficeName||x.DonorName||x.ProjectName||x.Title||x.Subject||x.OrganizationName||Object.values(x).filter(Boolean)[0]||"Record"}
function renderCards(rows){$("records").innerHTML=rows.map((x,i)=>`<div class=card onclick="recordDetail(current.rows[${current.rows.indexOf(x)}],current.key,current.name)"><h3>${esc(cardTitle(x))}</h3>${Object.entries(x).filter(([k,v])=>v&&k!=="Name").slice(0,5).map(([k,v])=>`<div class=meta><b>${esc(k.replace(/([a-z])([A-Z])/g,"$1 $2"))}:</b> ${esc(v)}</div>`).join("")}${x.Status?`<span class="badge ${String(x.Status).toLowerCase()}">${esc(x.Status)}</span>`:""}</div>`).join("")||"<div class=card>No records found.</div>"}
function recordDetail(x,k,n){let id=Object.values(x)[0];modal(n,`<div class=detailgrid>${Object.entries(x).map(([a,b])=>`<div class=field><small>${esc(a.replace(/([a-z])([A-Z])/g,"$1 $2"))}</small><b>${esc(b||"—")}</b></div>`).join("")}</div><div class=actions>${canAction(k,"Edit")?`<button class="btn blue" onclick='this.closest(".modal").remove();openForm(current.key,current.name,${JSON.stringify(x).replace(/'/g,"&#39;")})'>Edit</button>`:""}${canAction(k,"Delete")?`<button class="btn red" onclick="deleteRecord('${esc(k)}','${esc(id)}')">Delete</button>`:""}${k==="salary_slips"?`<button class="btn g" onclick="window.print()">Download / Print Salary Slip</button>`:""}</div>`)}
async function deleteRecord(k,id){if(!confirmSafe("Delete this record?"))return;try{await api("delete",{module:k,id});document.querySelector(".modal")?.remove();toast("Deleted");openModule(current.key,current.name)}catch(e){toast(e.message)}}
function confirmSafe(msg){return window.confirm(msg)} // only confirmation; no browser input prompts
async function openForm(k,n,record={}){try{let s=current.schema&&current.key===k?current.schema:await api("schema",{module:k});current.schema=s;let fields=s.fields.filter(f=>!["PasswordHash","KeySecretEncrypted","WebhookSecretEncrypted"].includes(f.name));modal((record&&Object.keys(record).length?"Edit ":"Add ")+n,`<form id=dataform>${fields.map(f=>`<label>${esc(f.label)}</label><input name="${esc(f.name)}" type="${f.type}" value="${esc(record[f.name]||"")}" ${f.readonly&&record[f.name]?"readonly":""}></input>`).join("")}<button class="btn g full" type=submit>SAVE</button></form>`);$("dataform").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target).entries());try{await api("save",{module:k,record:o,isEdit:!!record[fields[0]?.name]});document.querySelector(".modal")?.remove();toast("Saved successfully");openModule(k,n)}catch(er){toast(er.message)}}}catch(e){toast(e.message)}}
async function bell(){try{let r=await api("notifications");localStorage.SEEN_NOTIFICATIONS=JSON.stringify(r.map(x=>x.NotificationID));updateBell(r);modal("Notifications",r.map(x=>`<div class=card><h3>${esc(x.Title||"Notification")}</h3><p>${esc(x.Message||"")}</p><div class=meta>${esc(x.CreatedAt||"")}</div></div>`).join("")||"<p>No notifications.</p>")}catch(e){toast(e.message)}}
function updateBell(r){let seen=new Set(JSON.parse(localStorage.SEEN_NOTIFICATIONS||"[]")),n=(r||[]).filter(x=>!seen.has(x.NotificationID)).length,el=$("nb");if(el){el.textContent=n;el.hidden=!n}}
function showNewNotifications(){let r=B.notifications||[],seen=new Set(JSON.parse(localStorage.SEEN_NOTIFICATIONS||"[]")),fresh=r.filter(x=>!seen.has(x.NotificationID));updateBell(r);if(fresh.length){let x=fresh[0];modal(x.Title||"New Notification",`<p>${esc(x.Message||"")}</p><button class="btn g full" onclick="localStorage.SEEN_NOTIFICATIONS=JSON.stringify((B.notifications||[]).map(x=>x.NotificationID));document.querySelector('.modal').remove();updateBell(B.notifications)">Got it</button>`)}}

token=localStorage.getItem("sa_token")||"";let ACCESS=[];
function cset(x){localStorage.sa_boot=JSON.stringify({at:Date.now(),data:x})}function cget(){try{let x=JSON.parse(localStorage.sa_boot);return Date.now()-x.at<APP_CONFIG.CACHE_MINUTES*60000?x.data:null}catch(e){return null}}
async function login(){try{let d=await api("adminLogin",{user:$("user").value,password:$("pass").value});token=d.token;localStorage.setItem("sa_token",token);B={session:{kind:"admin",user:d.user},modules:d.modules,dashboard:null,notifications:[]};show();dashboard();refreshApp()}catch(e){$("msg").innerHTML=`<div class=error>${esc(e.message)}</div>`}}
function show(){$("login").hidden=true;$("app").hidden=false;$("who").textContent=B.session.user.Name||"Super Admin"}
async function logout(){try{if(token)await api("logout")}catch(e){}localStorage.removeItem("sa_token");localStorage.removeItem("sa_boot");$("app").hidden=true;$("login").hidden=false;B=null;token="";$("pass").value=""}
async function refreshApp(){try{B=await api("bootstrap");cset(B);show();dashboard();showNewNotifications()}catch(e){toast(e.message)}}
function canAction(){return true}
function dashboard(){let mods=B.modules||[];$("view").innerHTML=`<div class=globalsearch><input placeholder="Search anything across Sewangan ERP..." oninput="globalSearch(this.value)"><div id=gsr class=searchresults></div></div><div class=modulegrid>${mods.map(x=>`<button class=module data-name="${esc(x.ModuleName.toLowerCase())}" onclick="openModule('${x.ModuleKey}','${esc(x.ModuleName)}')"><i>${icon(x.ModuleKey)}</i><span>${esc(x.ModuleName)}</span></button>`).join("")}</div>`}
function modules(){dashboard()}
async function openModule(k,n){current={key:k,name:n,rows:[],schema:null};$("view").innerHTML="<div class=loading>Loading...</div>";try{let [r,s]=await Promise.all([api("list",{module:k}),api("schema",{module:k})]);current.rows=r;current.schema=s;$("view").innerHTML=`<div class=toolbar><button class=back onclick=dashboard()>←</button><h3>${esc(n)}</h3><button class="btn g" onclick="openForm('${k}','${esc(n)}')">+ Add</button></div><div class=modulesearch><input placeholder="Search anything in ${esc(n)}..." oninput="moduleSearch(this.value)"></div><div id=records class=cards></div>`;renderCards(r)}catch(e){$("view").innerHTML=`<div class=error>${esc(e.message)}</div>`}}
async function access(){$("view").innerHTML="<div class=loading>Loading access matrix...</div>";ACCESS=await api("mainAccess");let ds=[...new Set(ACCESS.map(x=>x.DesignationID))];$("view").innerHTML=`<div class=toolbar><button class=back onclick=dashboard()>←</button><h3>Main App Access</h3></div><div class=card><select id=des onchange=drawAccess()>${ds.map(x=>`<option>${esc(x)}</option>`).join("")}</select><div id=matrix></div></div>`;drawAccess()}
function drawAccess(){let d=$("des").value,rs=ACCESS.filter(x=>x.DesignationID===d);$("matrix").innerHTML=rs.map(r=>`<div class=card><b>${esc(r.ModuleKey)}</b><div class=actions>${["View","Add","Edit","Delete","Approve"].map(p=>`<label><input style="width:auto" class=ck data-m="${esc(r.ModuleKey)}" data-p="${p}" type=checkbox ${String(r[p]).toLowerCase()==="true"?"checked":""}> ${p}</label>`).join("")}</div><select class=sc data-m="${esc(r.ModuleKey)}"><option ${r.Scope==="Own"?"selected":""}>Own</option><option ${r.Scope==="Own + Direct Lower"?"selected":""}>Own + Direct Lower</option><option ${r.Scope==="Own + All Lower"?"selected":""}>Own + All Lower</option></select></div>`).join("")+`<button class="btn g full" onclick=saveAccess()>SAVE ACCESS</button>`}
async function saveAccess(){let d=$("des").value,rs=ACCESS.filter(x=>x.DesignationID===d);rs.forEach(r=>{document.querySelectorAll(`.ck[data-m="${r.ModuleKey}"]`).forEach(c=>r[c.dataset.p]=c.checked);r.Scope=document.querySelector(`.sc[data-m="${r.ModuleKey}"]`).value});await api("saveMainAccess",{rows:rs});toast("Access saved")}
(async()=>{if(token){let c=cget();if(c){B=c;show();dashboard()}try{B=await api("bootstrap");cset(B);show();dashboard();showNewNotifications()}catch(e){if(!B)logout()}}})();

const _memberDetail=recordDetail;
recordDetail=function(x,k,n){
 if(k!=="members")return _memberDetail(x,k,n);
 modal("Member Details",`<div class=detailgrid>${Object.entries(x).map(([a,b])=>`<div class=field><small>${esc(a.replace(/([a-z])([A-Z])/g,"$1 $2"))}</small><b>${esc(b||"—")}</b></div>`).join("")}</div><div class=actions><button class="btn g" onclick="designationDialog('${esc(x.MemberID)}','promote')">Promote</button><button class="btn blue" onclick="designationDialog('${esc(x.MemberID)}','demote')">Demote</button></div>`)
}
async function designationDialog(id,mode){
 try{let d=await api("designationMoves",{memberId:id}),list=d[mode]||[];if(!list.length)return toast("No designation available.");
 modal(mode==="promote"?"Promote Member":"Demote Member",`<p>Current: <b>${esc(d.current.DesignationName)}</b></p><label>New Designation</label><select id=newdes>${list.map(x=>`<option value="${esc(x.DesignationID)}">${esc(x.DesignationName)}</option>`).join("")}</select><label>Reason</label><textarea id=desreason></textarea><button class="btn g full" id=desgo>SAVE DESIGNATION</button>`);
 $("desgo").onclick=async()=>{try{let r=await api("changeDesignation",{memberId:id,designationId:$("newdes").value,reason:$("desreason").value});document.querySelectorAll(".modal").forEach(x=>x.remove());toast(r.type+": "+r.newDesignation);openModule("members","Members")}catch(e){toast(e.message)}}}catch(e){toast(e.message)}
}
